[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log

[program:postgresql]
command=/usr/lib/postgresql/%(ENV_PG_MAJOR)s/bin/postgres -D /var/lib/postgresql/data
user=postgres
autostart=true
autorestart=true

[program:redis]
command=redis-server --protected-mode no
autostart=true
autorestart=true
